# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grantest.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bBeelzebub = QtWidgets.QLabel(self.centralwidget)
        self.bBeelzebub.setGeometry(QtCore.QRect(10, 10, 151, 151))
        self.bBeelzebub.setText("")
        self.bBeelzebub.setPixmap(QtGui.QPixmap("resources/finals/beelzebub.png"))
        self.bBeelzebub.setObjectName("bBeelzebub")
        self.bCharlotta = QtWidgets.QLabel(self.centralwidget)
        self.bCharlotta.setGeometry(QtCore.QRect(170, 10, 151, 151))
        self.bCharlotta.setText("")
        self.bCharlotta.setPixmap(QtGui.QPixmap("resources/finals/charlotta.png"))
        self.bCharlotta.setObjectName("bCharlotta")
        self.bDjeeta = QtWidgets.QLabel(self.centralwidget)
        self.bDjeeta.setGeometry(QtCore.QRect(330, 10, 151, 151))
        self.bDjeeta.setText("")
        self.bDjeeta.setPixmap(QtGui.QPixmap("resources/finals/djeeta.png"))
        self.bDjeeta.setObjectName("bDjeeta")
        self.bFerry = QtWidgets.QLabel(self.centralwidget)
        self.bFerry.setGeometry(QtCore.QRect(490, 10, 151, 151))
        self.bFerry.setText("")
        self.bFerry.setPixmap(QtGui.QPixmap("resources/finals/ferry.png"))
        self.bFerry.setObjectName("bFerry")
        self.bGran = QtWidgets.QLabel(self.centralwidget)
        self.bGran.setGeometry(QtCore.QRect(10, 170, 151, 151))
        self.bGran.setText("")
        self.bGran.setPixmap(QtGui.QPixmap("resources/finals/gran.png"))
        self.bGran.setObjectName("bGran")
        self.bKatalina = QtWidgets.QLabel(self.centralwidget)
        self.bKatalina.setGeometry(QtCore.QRect(170, 170, 151, 151))
        self.bKatalina.setText("")
        self.bKatalina.setPixmap(QtGui.QPixmap("resources/finals/katalina.png"))
        self.bKatalina.setObjectName("bKatalina")
        self.bLadiva = QtWidgets.QLabel(self.centralwidget)
        self.bLadiva.setGeometry(QtCore.QRect(330, 170, 151, 151))
        self.bLadiva.setText("")
        self.bLadiva.setPixmap(QtGui.QPixmap("resources/finals/ladiva.png"))
        self.bLadiva.setObjectName("bLadiva")
        self.bLancelot = QtWidgets.QLabel(self.centralwidget)
        self.bLancelot.setGeometry(QtCore.QRect(490, 170, 151, 151))
        self.bLancelot.setText("")
        self.bLancelot.setPixmap(QtGui.QPixmap("resources/finals/lancelot.png"))
        self.bLancelot.setObjectName("bLancelot")
        self.bLowain = QtWidgets.QLabel(self.centralwidget)
        self.bLowain.setGeometry(QtCore.QRect(10, 330, 151, 151))
        self.bLowain.setText("")
        self.bLowain.setPixmap(QtGui.QPixmap("resources/finals/lowain.png"))
        self.bLowain.setObjectName("bLowain")
        self.bMetera = QtWidgets.QLabel(self.centralwidget)
        self.bMetera.setGeometry(QtCore.QRect(170, 330, 151, 151))
        self.bMetera.setText("")
        self.bMetera.setPixmap(QtGui.QPixmap("resources/finals/metera.png"))
        self.bMetera.setObjectName("bMetera")
        self.bNarmaya = QtWidgets.QLabel(self.centralwidget)
        self.bNarmaya.setGeometry(QtCore.QRect(330, 330, 151, 151))
        self.bNarmaya.setText("")
        self.bNarmaya.setPixmap(QtGui.QPixmap("resources/finals/narmaya.png"))
        self.bNarmaya.setObjectName("bNarmaya")
        self.bPercival = QtWidgets.QLabel(self.centralwidget)
        self.bPercival.setGeometry(QtCore.QRect(490, 330, 151, 151))
        self.bPercival.setText("")
        self.bPercival.setPixmap(QtGui.QPixmap("resources/finals/percival.png"))
        self.bPercival.setObjectName("bPercival")
        self.bSoriz = QtWidgets.QLabel(self.centralwidget)
        self.bSoriz.setGeometry(QtCore.QRect(10, 490, 151, 151))
        self.bSoriz.setText("")
        self.bSoriz.setPixmap(QtGui.QPixmap("resources/finals/soriz.png"))
        self.bSoriz.setObjectName("bSoriz")
        self.bVaseraga = QtWidgets.QLabel(self.centralwidget)
        self.bVaseraga.setGeometry(QtCore.QRect(170, 490, 151, 151))
        self.bVaseraga.setText("")
        self.bVaseraga.setPixmap(QtGui.QPixmap("resources/finals/vaseraga.png"))
        self.bVaseraga.setObjectName("bVaseraga")
        self.bZeta = QtWidgets.QLabel(self.centralwidget)
        self.bZeta.setGeometry(QtCore.QRect(330, 490, 151, 151))
        self.bZeta.setText("")
        self.bZeta.setPixmap(QtGui.QPixmap("resources/finals/zeta.png"))
        self.bZeta.setObjectName("bZeta")
        self.bZooey = QtWidgets.QLabel(self.centralwidget)
        self.bZooey.setGeometry(QtCore.QRect(490, 490, 151, 151))
        self.bZooey.setText("")
        self.bZooey.setPixmap(QtGui.QPixmap("resources/finals/zooey.png"))
        self.bZooey.setObjectName("bZooey")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
